"""initial migration

Revision ID: 022717407100
Revises: 
Create Date: 2018-06-05 16:06:28.503763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022717407100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
