"""add confirmed status column

Revision ID: 580d0f2bb850
Revises: 022717407100
Create Date: 2018-06-11 17:07:12.346199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580d0f2bb850'
down_revision = '022717407100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'confirmed')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
